# Generated by Django 2.2.19 on 2021-04-01 15:24

from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_external_enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCourseSettings',
            fields=[
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('external_course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_platform', models.CharField(blank=True, max_length=255, null=True)),
                ('other_course_settings', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True)),
            ],
        ),
    ]
