# Generated by Django 2.2.16 on 2021-03-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
        ('openedx_external_enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCourseSettings',
            fields=[
                ('course_overview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course_overviews.CourseOverview')),
                ('external_course_id', models.CharField(blank=True, max_length=255)),
                ('external_platform', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
