# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1
workflows:
  version: 2.1
  test:
    jobs:
      - test:
          matrix:
            parameters:
              python_version: ["3.5", "3.8"]
jobs:
  test:
    parameters:
      python_version:
        type: string
    working_directory: ~/repo<< parameters.python_version >>
    docker:
      - image: 'circleci/python:<< parameters.python_version >>'
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements/test.txt" }}
      - run:
          name: Activating virtualenv and installing dependencies.
          command: |
            test -d venv || virtualenv -p python3 ./venv
            . venv/bin/activate
            make install-dev-dependencies

      - save_cache:
          paths:
            - ./.tox
            - ./venv
          key: v2-dependencies-{{ checksum "requirements/test.txt" }}

      - run:
          name: Run Python tests and quality tests.
          command: |
            . venv/bin/activate
            export TOX_ENV=$PY_ENV
            export TOXENV=${TOX_ENV//./}
            make run-tests

    environment:
      - PY_ENV: py<< parameters.python_version >>
